require(path_p_vanilla_changes .. "entity")
require(path_p_vanilla_changes .. "item")
require(path_p_vanilla_changes .. "recipe")
require(path_p_vanilla_changes .. "resource")
require(path_p_vanilla_changes .. "technology")