nuclear.debug.log("Init items...")

require(no_path_p_items .. "armor")
require(no_path_p_items .. "element")
require(no_path_p_items .. "equipment")
require(no_path_p_items .. "fluoride")
require(no_path_p_items .. "fuel")
require(no_path_p_items .. "reactor")
require(no_path_p_items .. "thorium")
require(no_path_p_items .. "yellowcake")
